In [14]:
import numpy as np
import os
import itertools

n_vac = 1

oct_sites_0 = np.zeros((3,3))
k = 0

for [i,j] in itertools.combinations([0, 1, 2],2):
    oct_sites_0[k,[i,j]] = 0.5
    k += 1
    
oct_sites_1 = np.ones((3,3))
k = 0

for [i,j] in itertools.combinations([0, 1, 2],2):
    oct_sites_1[k,[i,j]] = 0.5
    k += 1

oct_sites_unit = np.vstack([oct_sites_0, oct_sites_1])

n_iter = np.clip(n_vac, a_min = 1, a_max = None)

oct_sites = np.vstack([oct_sites_unit + i*0.5 for i in range(n_iter)])

oct_sites_unique = np.unique(oct_sites, axis = 0)

print(oct_sites_unique)

[[0.  0.5 0.5]
 [0.5 0.  0.5]
 [0.5 0.5 0. ]
 [0.5 0.5 1. ]
 [0.5 1.  0.5]
 [1.  0.5 0.5]]


In [15]:
n_vac = 1
tet_sites_0 = np.zeros((12,3))
k = 0
for [i,j] in itertools.combinations([0, 1, 2],2):
    tet_sites_0[4*k:4*k+4,[i,j]] = np.array( [[0.5 , 0.25],
                                          [0.25, 0.5],
                                          [0.5 , 0.75],
                                          [0.75, 0.5] ])

    k += 1
tet_sites_1 = np.ones((12,3))
k = 0
for [i,j] in itertools.combinations([0, 1, 2],2):
    tet_sites_1[4*k:4*k+4,[i,j]] = np.array( [[0.5 , 0.25],
                                          [0.25, 0.5],
                                          [0.5 , 0.75],
                                          [0.75, 0.5] ])

    k += 1

tet_sites_unit = np.vstack([tet_sites_0, tet_sites_1])

n_iter = np.clip(n_vac, a_min = 1, a_max = None)

tet_sites = np.vstack([tet_sites_unit + i*0.5 for i in range(n_iter)])

tet_sites_unique = np.unique(tet_sites, axis = 0)

print(tet_sites_unique.shape)

(24, 3)


In [16]:
n_vac = 2

correction = np.clip((n_vac - 1), a_min=0, a_max = None)

n_sites = n_vac + 2 + correction

upper_lim = 0.75 + correction * 0.5

diag_sites_0 = np.hstack( [

    np.linspace(0.25, upper_lim, n_sites).reshape(n_sites,1),
    np.linspace(0.25, upper_lim, n_sites).reshape(n_sites,1),
    np.linspace(0.25, upper_lim, n_sites).reshape(n_sites,1),
])

diag_sites_1 = np.array([ 
                        [0.25, 0.75, 0.75],
                        [0.75, 0.25, 0.25],
                        [0.75, 0.25, 0.75],
                        [0.25, 0.75, 0.25],
                        [0.75, 0.75, 0.25],
                        [0.25, 0.25, 0.75]
                    ])    


n_iter = np.clip(n_vac, a_min = 1, a_max = None)

diag_sites_1 = np.vstack([diag_sites_1 + i*0.5 for i in range(n_iter)])

diag_sites_unit = np.vstack([diag_sites_0, diag_sites_1])

diag_sites_unique = np.unique(diag_sites_unit, axis = 0)

print(diag_sites_unique)

[[0.25 0.25 0.25]
 [0.25 0.25 0.75]
 [0.25 0.75 0.25]
 [0.25 0.75 0.75]
 [0.5  0.5  0.5 ]
 [0.75 0.25 0.25]
 [0.75 0.25 0.75]
 [0.75 0.75 0.25]
 [0.75 0.75 0.75]
 [0.75 0.75 1.25]
 [0.75 1.25 0.75]
 [0.75 1.25 1.25]
 [1.   1.   1.  ]
 [1.25 0.75 0.75]
 [1.25 0.75 1.25]
 [1.25 1.25 0.75]
 [1.25 1.25 1.25]]


In [17]:
central_sites = np.array( [ [(i+1)*0.5,(i+1)*0.5, (i+1)*0.5] for i in range(n_vac)] )

print(central_sites)

[[0.5 0.5 0.5]
 [1.  1.  1. ]]


In [18]:
n_atoms = 2
N = 0
sites = [[0.2,0.5], [0.1,0.2], [0.4,0.2],[0, 1] ]

for [i,j] in itertools.combinations_with_replacement([0, 1, 2, 3],n_atoms):

    N += 1
    print(i,j)
    sites[i], sites[j]


0 0
0 1
0 2
0 3
1 1
1 2
1 3
2 2
2 3
3 3


In [19]:
n_vac = 10
central_sites = [ (i+1)*np.array([0.5, 0.5, 0.5]) for i in range(n_vac)]
print(central_sites)

[array([0.5, 0.5, 0.5]), array([1., 1., 1.]), array([1.5, 1.5, 1.5]), array([2., 2., 2.]), array([2.5, 2.5, 2.5]), array([3., 3., 3.]), array([3.5, 3.5, 3.5]), array([4., 4., 4.]), array([4.5, 4.5, 4.5]), array([5., 5., 5.])]


In [23]:
available_sites = [oct_sites_unique, tet_sites_unique, diag_sites_unique, central_sites]

print(available_sites[1])

available_sites[1] = np.delete(available_sites[1], 0, axis = 0)

print(available_sites[1])

[[0.   0.25 0.5 ]
 [0.   0.5  0.25]
 [0.   0.5  0.75]
 [0.   0.75 0.5 ]
 [0.25 0.   0.5 ]
 [0.25 0.5  0.  ]
 [0.25 0.5  1.  ]
 [0.25 1.   0.5 ]
 [0.5  0.   0.25]
 [0.5  0.   0.75]
 [0.5  0.25 0.  ]
 [0.5  0.25 1.  ]
 [0.5  0.75 0.  ]
 [0.5  0.75 1.  ]
 [0.5  1.   0.25]
 [0.5  1.   0.75]
 [0.75 0.   0.5 ]
 [0.75 0.5  0.  ]
 [0.75 0.5  1.  ]
 [0.75 1.   0.5 ]
 [1.   0.25 0.5 ]
 [1.   0.5  0.25]
 [1.   0.5  0.75]
 [1.   0.75 0.5 ]]
[[0.   0.5  0.25]
 [0.   0.5  0.75]
 [0.   0.75 0.5 ]
 [0.25 0.   0.5 ]
 [0.25 0.5  0.  ]
 [0.25 0.5  1.  ]
 [0.25 1.   0.5 ]
 [0.5  0.   0.25]
 [0.5  0.   0.75]
 [0.5  0.25 0.  ]
 [0.5  0.25 1.  ]
 [0.5  0.75 0.  ]
 [0.5  0.75 1.  ]
 [0.5  1.   0.25]
 [0.5  1.   0.75]
 [0.75 0.   0.5 ]
 [0.75 0.5  0.  ]
 [0.75 0.5  1.  ]
 [0.75 1.   0.5 ]
 [1.   0.25 0.5 ]
 [1.   0.5  0.25]
 [1.   0.5  0.75]
 [1.   0.75 0.5 ]]


In [21]:
np.argmax(np.array([0.1, 0.2 ,0.3]) - np.array([0.1, 0.2, 0.3]))

lst = []


arr = np.random.rand(10,10)

